[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.2.1" }
selene = { source = "Kampfkarren/selene", version = "0.28.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "2.1.0" }
wally = { source = "UpliftGames/wally", version = "0.3.2" }
